# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Ben Pritchard
tagline:          'A brand new full stack web developer, looking to work for social causes.'
description:      'A brand new full stack web developer, looking to work for social causes.'
url:              http://www.benpritchard.me
baseurl:          /

author:
  name:           'Ben Pritchard'
  url:            http://www.benpritchard.me

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
